title: "SoteroLab"
email: osoterolab@gmail.com
timezone: UTC
baseurl: "/soterolab"
permalink: "/:title/"
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Authors
authors:
  sotero:
    name: Sotero
    display_name: SoteroLab
    avatar: 'assets/images/sotero_logo2.png'
    email: osoterolab@gmail.com
    instagram: "https://www.instagram.com/osoterolab/"
    description: "Laboratório compromissado social e politicamente na discussão e produção de conhecimentos sobre tecnologias da informação."


# Social
social:
  instagram: https://www.instagram.com/osoterolab/
  linkedin: https://www.linkedin.com/company/soterolab/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
